[package]
name = "bevy-dlc"
version = "1.1.2"
edition = "2024"
rust-version = "1.93"
authors = ["Kirk <github.com/captkirk88>"]
description = "DLC (downloadable content) management for Bevy games"
license = "MIT"
readme = "README.md"
repository = "https://github.com/captkirk88/bevy-dlc"
categories = ["game-development"]
keywords = ["bevy", "dlc"]
exclude = ["tests/*","examples/*", "benches/*", "assets/*"]

[features]
default = []

[dependencies]
bevy = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = { version = "0.22" }
thiserror = "2.0"
rand = "0.10"
aes-gcm = "0.10"
clap = { version = "4.5", features = ["derive"] }
hex = "0.4"
flate2 = "1.1"
tar = "0.4"
dashmap = "6.1"
once_cell = "1.21"
zeroize = "1.8"
ring = "0.17"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
secure-gate = { version = "0.7.0-rc.14", features = ["secure", "rand", "cloneable", "ct-eq"] }
byte-aes = "0.2.2"
rayon = "1.11"

[dev-dependencies]
assert_cmd = "2.1"
predicates = "3.1"
tempfile = "3.6"
secure = { version = "0.3" }

[profile.release]
opt-level = "z"
strip = "symbols"
lto = "thin"
codegen-units = 1
panic = 'abort'

[profile.release.package."*"]
opt-level = "z"
strip = "symbols"
codegen-units = 1

[[example]]
name = "real"
path = "examples/real/main.rs"
